env:
  CLDR_PRODUCTION: "/SHOULD_NOT_BE_USED"
  CIRRUS_CLONE_DEPTH: 99
  ELIXIR_ASSERT_TIMEOUT: 2000
  ELIXIRC_OPTS: "--warnings-as-errors"
  ERLC_OPTS: "+warning_as_errors"
  LANG: C.UTF-8
  MIX_ENV: test

test_task:
  container:
    matrix:
      image: elixir:latest
  compile_script:
    mix local.hex --force;
    mix local.rebar --force;
    mix compile
  test_script: mix test




