env:
  CLDR_PRODUCTION: "/SHOULD_NOT_BE_USED"
  CIRRUS_CLONE_DEPTH: 99
  ELIXIR_ASSERT_TIMEOUT: 2000
  ELIXIRC_OPTS: "--warnings-as-errors"
  ERLC_OPTS: "+warning_as_errors"
  LANG: C.UTF-8
  MIX_ENV: test

test_task:
  container:
    matrix:
      image: elixir:latest
      image: elixir:1.8.2
      image: elixir:1.8.2-otp-22
  mix_cache:
    folder: deps
    fingerprint_script: cat mix.lock
    populate_script:
      mix local.hex --force;
      mix local.rebar --force;
      mix deps.get
  compile_script:
    mix local.hex --force;
    mix local.rebar --force;
    mix compile
  test_script: mix test




